### ISSUE TITLE
Why did you choose your field of career? Who is your early stage hero?

### ISSUE THREAD

**Issue by imondal007** [torifat/ama#1]
Most people love to work on back end, so far I know you work on front end stack. I am a Junior Developer too, self taught and working with react eco system. I would like to know your thought and philosophy behind choosing front-end.

I also want to know how did you started writing code, who were your inspiration at that time.

TIA

**Comment by torifat** [comment]
I wasn't always a front-end dev. I started my carrier with desktop applications. Then I mostly did back-end and some front-end work for quite some time. But, I was really intrigued by the amount of innovation in front-end. Though some people were very unhappy and annoyed _(they still are 😉)_ about it. For me, it was just the opposite. I was very excited about the future of it and decided to do only front-end.

I started coding when I was in school. My cousin's friend developed a custom software for my uncle's company. And I was very surprised by the fact that you could do such awesome stuff with programming. So he was kind of the early inspiration for me.
