### ISSUE TITLE
How'd you go from working at Backpack to Atlassian?

### ISSUE THREAD

**Issue by mii9000** [torifat/ama#3]
Would really appreciate if you can briefly write how you got from working in Bangladesh to working in a company like Atlassian in Australia. I think Bangladeshi devs like myself can take inspiration from your achievements.

**Comment by torifat** [comment]
Nothing special really. I created a profile in [StackOverflow Jobs](https://stackoverflow.com/jobs) with a few criteria. Like location _(Australia/Canada)_, sponsors VISA and, provides relocation, etc. Then I got an email with few options and one of them was Atlassian. And, I just applied and went through the whole interview process.
